### PR TITLE
Allowing targeting of bundle min files

### PR DESCRIPTION
**Pull request by rockstardev**
Hey @meziantou,

I like what you did - I just needed option to target min version of bundle so I've added it. Let me know if you can merge and publish NuGet update so that I can target new assembly in our solution.

### CODE REVIEW

**Comment by meziantou** [comment]
Thank for the improvement!

Just to clarify, you want to be able to target the unminified bundle file? file (`bundle.js` instead of `bundle.min.js`)

**Comment by rockstardev** [comment]
@meziantou I want to target minified bundle file. The "problem" is that BundleMinifier generates two bundle files: `bundle.js` and `bundle.min.js`

When you are using your extension you of course do `<bundle name="bundle.js" />`

But if you want to target `bundle.min.js` there is no option - I was now looking if there is way to tell BundleMinifier to only generate MIN version... but there isn't.

Also it seems Mads wanted to do Helper himself... but didn't find time... here: https://github.com/madskristensen/BundlerMinifier/wiki#aspnet-helpers

So, we can maybe open new issue there and get this project joined into solution - it makes sense, this is missing piece.

**Comment by rockstardev** [comment]
OK, seems there is a way to signal creation of `min` file to BundleMinifier... you use name that contains **min** like `bundle.min.js`. 

If you set output file to `bundle.js` then you will end up with 2 files: `bundle.js` and `bundle.min.js` and you won't be able to target 2nd.

Having this option to target one of those two files would be useful in those cases where you have 2 files. Otherwise for people who don't care and bundle file directly to `bundle.min.js` and not use `sourceMap:true` option - they wouldn't care about it.

**Comment by rockstardev** [comment]
If you want to look at concrete code - how I am using all this see this: https://github.com/btcpayserver/btcpayserver/issues/47

**Pull request merged**
